Test/urls.py
from django.urls import path, include
import NBAStream.views
urlpatterns = [
    path('', NBAStream.views.index),
    path('web/', include("Web.urls", namespace='web')),
    path('user/', include("User.urls", namespace='user')),
    path('nbastream/', include("NBAStream.urls", namespace='nbastream')),
    path('admin/', include("Admin.urls", namespace='admin')),
    path('blog/', include("Blog.urls", namespace='blog'),),

]

User/urls.py
from django.urls import path, re_path
from .views import *
app_name = 'User'
urlpatterns = [
    path('index/', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    re_path('^setting/(?:(?P<flag>\w+)/(page-(?P<current_page>\d+)/)?)?', setting, name="setting"),
]

Web/urls.py
from django.urls import path, re_path
from .views import *
app_name = 'Web'
urlpatterns = [
    path('about/', about, name='about'),
    re_path('^notice/(?:page-(?P<noticeid>\d+)/)?', notice, name='notice'),
    path('board/', board, name='board-na'),
    path('board/<int:current_page>/', board, name='board'),
]

User/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    type = models.IntegerField(default=0)
    email = models.EmailField(default='')
    registryTime = models.DateTimeField()


User/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from .UserForm import *
from datetime import *
from util.Pagination import *
from Web.models import Message
# Create your views here.


def index(request):
    try:
        userid = request.session['userid']
        user = User.objects.get(id=userid)
    except:
        user = None
    return render(request, "User/index.html", {'user': user})


def login(request):
    message = ""
    error_message = ""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        autologin = request.POST.get('autologin')
        try:
            user_origin = User.objects.get(username=username)
        except:
            error_message = '用户名不存在'
        else:
            if password == user_origin.password:#验证成功
                response = HttpResponseRedirect("/")
                request.session['userid'] = user_origin.id
                if not autologin:
                    request.session.set_expiry(0)
                return response
            else:
                error_message = '密码错误'
    return render(request, 'User/login.html', {'message': message, 'error_message': error_message})


def logout(request):
    response = HttpResponseRedirect(reverse("User:login"))
    try:
        del request.session['userid']
    except KeyError:
        pass
    return response


def register(request):
    message = ""
    error_message = ""
    if request.method == "POST":
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        email = request.POST.get('email')
        if not all((username, password1, password2)):
            error_message = "用户名或密码不能为空"
        elif password1 != password2:
            error_message = "两次密码不一致"
        else:
            try:
                User.objects.get(username=username)
                error_message = "用户名已存在"
            except:
                User.objects.create(username=username,password=password1,
                                    type=0, email=email,
                                    registryTime=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
                message = "注册成功"
    context = {'message': message, 'error_message': error_message, 'user':None}
    return render(request, 'User/register.html', context)


def setting(request, flag="", current_page=1):
    info_error_message = ""
    info_message = ""
    password_error_message = ""
    password_message = ""
    try:
        userid = request.session["userid"]
        user = User.objects.get(id=userid)
    except Exception as e:
        print(str(e))
    if request.method == "POST":
        if flag == "info":
            try:
                email = request.POST.get("email")
                user.email = email
                user.save()
                info_message = "修改成功"
            except Exception as e:
                info_error_message = str(e)
        elif flag == "password":
            try:
                password_old = request.POST.get("password_old")
                password1 = request.POST.get("password1")
                password2 = request.POST.get("password2")
                if password1!=password2 :
                    password_error_message = "两次输入的密码不一致"
                elif password_old != user.password:
                    password_error_message = "旧密码输入不正确"
                else:
                    user.password = password1
                    user.save()
                    password_message = "修改成功"
            except Exception as e:
                password_error_message = str(e)
    my_all_message = Message.objects.filter(user_id=userid).order_by("-createTime")
    show_my_message, page_list, current_page, previous_page, next_page, last_page = paginate(my_all_message, current_page, 3)
    context = {"flag": flag, 'myuser': user, 'show_my_message': show_my_message,
               'user': user, 'page_list': page_list,
               'current_page': current_page, 'next_page': next_page,
               'previous_page': previous_page, 'last_page': last_page,
               'info_message': info_message, 'info_error_message': info_error_message,
               'password_message': password_message, 'password_error_message': password_error_message}
    return render(request, "User/setting.html", context)


User/templates/User/board.html
{% extends "main.html" %}
{% block content %}
    {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
    {% endif %}
    {% if success_message %}
        <p class="text-success">{{ success_message }}</p>
    {% endif %}
    <form action="{% url "User:board" 1 %}" method="post" class=" mb-sm-4">
        {% csrf_token %}
        <textarea name="content" id="editor1" class="form-control"></textarea>
        <script>
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace( 'editor1' );
        </script>
        <input type="submit" value="发表" class="btn btn-primary btn-lg float-right mt-sm-4">
        <div class="clearfix"></div>
    </form>
    {% for item in show_message %}
    <div class="card mb-sm-4">
        <div class="row" style="padding: 10px;">
            <div class="col-sm-2">
                <img class="rounded-circle mx-auto d-block" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="60" height="60">
                <div class="text-center">
                    <strong>{{ item.user.username }}</strong>
                </div>
            </div>
            <div class="col-sm-10">
                {% autoescape off %}
                    <p class="card-text">
                        {{ item.content }}
                    </p>
                {% endautoescape %}

                <div class="text-right">
                    {{ item.createTime|date:"Y-m-d H:i:s" }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
	{% if page_list %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if current_page != 1 %}
            <li class="page-item">
                <a class="page-link" href="{% url "User:board" previous_page %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        {% endif %}
            {% for i in page_list %}
                {% if i != current_page %}
                    <li class="page-item">
                {% else %}
                    <li class="page-item active">
                {% endif %}
                <a class="page-link" href="{% url "User:board" i %}">{{ i }}</a>
            </li>
            {% endfor %}
        {% if current_page != last_page %}
            <li class="page-item">
                <a class="page-link" href="{% url "User:board" next_page %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        {% endif %}
        </ul>
    </nav>
	{% endif %}

{% endblock %}
{% block head %}
    <title>留言板</title>
{% endblock %}

User/templates/User/index.html
{% extends "base.html" %}
{% block body %}
    <p>用户页面(未完成)</p>
{% endblock %}
{% block head %}
    <title>个人中心</title>
{% endblock %}

User/templates/User/login.html
{% extends "base.html" %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 border" style="border: grey;border-radius: 15px;padding: 20px;">
                {% if message %}
                    <p class="text-success">{{ message }}</p>
                {% endif %}
				{% if error_message %}
                    <p class="text-danger">{{ error_message }}</p>
                {% endif %}
                <form action="{% url 'user:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleFormControlInput1">用户名</label>
                        <input type="text" class="form-control" name="username" placeholder="请输入用户名">
                        <!--<small class="form-text text-muted" name=""></small>-->
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">密码</label>
                        <input type="password" class="form-control" name="password" placeholder="请输入密码">
                        <!--<small class="form-text text-muted" name=""></small>-->
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" name="autologin" checked>
                        <label class="form-check-label">下次自动登录</label>
                    </div>
                    <div class="form-group text-center mt-sm-4">
                        <input class="btn btn-primary btn-block" type="submit" value="登录">
                    </div>

                    <div class="form-group">
                        <a class="float-sm-left" href="#">忘记密码?</a>
                        <a class="float-sm-right" href="{% url "User:register" %}">立即注册</a>
                    </div>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
{% endblock %}
{% block head %}
    <title>登录</title>
{% endblock %}

User/templates/User/register.html
{% extends "base.html" %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 border" style="border: grey;border-radius: 15px;padding: 20px;">
                {% if message %}
                    <p class="text-success">{{ message }}</p>
                {% endif %}
				{% if error_message %}
                    <p class="text-danger">{{ error_message }}</p>
                {% endif %}
                <form method="post" action="{% url 'user:register' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleFormControlInput1">用户名</label>
                        <input type="text" class="form-control" name="username" placeholder="请输入用户名">
                        <!--<small class="form-text text-muted" name=""></small>-->
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">邮箱</label>
                        <input type="text" class="form-control" name="email" placeholder="请输入邮箱">
                        <!--<small class="form-text text-muted" name=""></small>-->
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">密码</label>
                        <input type="password" class="form-control" name="password1" placeholder="请输入密码">
                        <!--<small class="form-text text-muted" name=""></small>-->
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">再次确认密码</label>
                        <input type="password" class="form-control" name="password2" placeholder="请再次输入密码">
                        <!--<small class="form-text text-muted" name=""></small>-->
                    </div>
                        <input class="btn btn-primary btn-block mt-sm-4" type="submit" value="注册">
                        <a href="{% url "User:login" %}" class="mt-sm-3 float-right">已有账号,直接登录</a>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
{% endblock %}
{% block head %}
    <title>注册</title>
{% endblock %}

User/templates/User/setting.html
{% extends "base.html" %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="nav flex-column nav-pills nav-justified" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    {% if flag == "info" or flag == "" or flag == None %}
                        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">
                    {% else %}
                        <a class="nav-link" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">
                    {% endif %}
                        修改资料
                    </a>
                    {% if flag == "password" %}
                        <a class="nav-link active" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">
                    {% else %}
                        <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">
                    {% endif %}
                        修改密码</a>
                    {% if flag == "comment" %}
                        <a class="nav-link active" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">
                    {% else %}
                        <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">
                    {% endif %}
                        我的评论
                    </a>
                    {% if flag == "message" %}
                        <a class="nav-link active" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">
                    {% else %}
                        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">
                    {% endif %}
                        我的留言
                    </a>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="tab-content" id="v-pills-tabContent">
                    {% if flag == "info" or flag == "" or flag == None %}
                        <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                    {% else %}
                        <div class="tab-pane fade show" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                    {% endif %}
                        <div class="row">
                            <div class="col-sm-6">
                                {% if info_message %}
                                    <p class="text-success">{{ info_message }}</p>
                                {% endif %}
                                {% if info_error_message %}
                                    <p class="text-danger">{{ info_error_message }}</p>
                                {% endif %}
                                <form action="{% url "User:setting" "info" %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="exampleFormControlInput1">用户名</label>
                                        <input type=text class="form-control" name="username" placeholder="请输入用户名" value="{{ user.username }}" readonly>
                                        <!--<small class="form-text text-muted" name=""></small>-->
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleFormControlInput1">用户类型</label>
                                        <input type="text" class="form-control" name="type" readonly value="{{ user.type }}">
                                        <!--<small class="form-text text-muted" name=""></small>-->
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleFormControlInput1">邮箱</label>
                                        <input type="email" class="form-control" name="email" placeholder="请输入邮箱" value="{{ user.email }}">
                                        <!--<small class="form-text text-muted" name=""></small>-->
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleFormControlInput1">注册时间</label>
                                        <input type="text" class="form-control" name="registryTime" readonly value="{{ user.registryTime|date:"Y-m-d H:i:s" }}">
                                    </div>

                                    <div class="form-group text-center mt-sm-4">
                                        <input class="btn btn-primary btn-block" type="submit" value="保存">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% if flag == "password" %}
                        <div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                    {% else %}
                        <div class="tab-pane fade show" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                    {% endif %}
                        <div class="row">
                            <div class="col-sm-6">
                                {% if password_message %}
                                    <p class="text-success">{{ password_message }}</p>
                                {% endif %}
                                {% if password_error_message %}
                                    <p class="text-danger">{{ password_error_message }}</p>
                                {% endif %}
                                <form action="{% url "User:setting" "password" %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="exampleFormControlInput1">旧密码</label>
                                        <input type="password" class="form-control" name="password_old" placeholder="请输入密码">
                                        <!--<small class="form-text text-muted" name=""></small>-->
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleFormControlInput1">新密码</label>
                                        <input type="password" class="form-control" name="password1" placeholder="请输入密码">
                                        <!--<small class="form-text text-muted" name=""></small>-->
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleFormControlInput1">再次确认密码</label>
                                        <input type="password" class="form-control" name="password2" placeholder="请再次输入密码">
                                        <!--<small class="form-text text-muted" name=""></small>-->
                                    </div>

                                    <div class="form-group text-center mt-sm-4">
                                        <input class="btn btn-primary btn-block" type="submit" value="保存">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% if flag == "comment" %}
                        <div class="tab-pane fade show active" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                    {% else %}
                        <div class="tab-pane fade show" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                    {% endif %}
                        <p>正在开发中...</p>
                    </div>
                    {% if flag == "message" %}
                        <div class="tab-pane fade show active" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
                    {% else %}
                        <div class="tab-pane fade show" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
                    {% endif %}
                    {% if not show_my_message %}
                        <p>未曾留言</p>
                    {% endif %}
                    {% for item in show_my_message %}
                        <div class="card  mb-sm-4">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        {% autoescape off %}
                                            <p class="card-text">
                                                {{ item.content }}
                                            </p>
                                        {% endautoescape %}
                                        <div class="text-right">
                                            {{ item.createTime|date:"Y-m-d H:i:s" }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    {% if page_list %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-center">
                            {% if current_page != 1 %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url "User:setting" "message" %}page-{{ previous_page }}/" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                            {% endif %}
                                {% for i in page_list %}
                                    {% if i != current_page %}
                                        <li class="page-item">
                                    {% else %}
                                        <li class="page-item active">
                                    {% endif %}
                                            <a class="page-link" href="{% url "User:setting" "message" %}page-{{ i }}/">{{ i }}</a>
                                        </li>
                                {% endfor %}
                                {% if current_page != last_page %}
                                    <li class="page-item">
                                        <a class="page-link" href="{% url "User:setting" "message" %}page-{{ next_page }}/" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block head %}
    <title>个人信息</title>
{% endblock %}