Admin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
app_name = 'Admin'
urlpatterns = [
    path('index/', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('changepassowrd/', changepassowrd, name='changepassowrd'),
    re_path('^notice/(?:page-(?P<current_page>\d+)/)?', notice, name='notice'),
    path('deletenotice/<int:noticeid>/', delete_notice, name='delete_notice'),
    re_path('^visit/(?:page-(?P<current_page>\d+)/)?', visit, name='visit'),
    re_path('^message/(?:page-(?P<current_page>\d+)/)?', message, name='message'),
    path('deletemessage/<int:messageid>/', delete_message, name='delete_message'),
    path('deletevisit/<int:visitorid>/', delete_visitor, name='delete_visitor'),
    re_path('^userSetting/(?:page-(?P<current_page>\d+)/)?', userSetting, name='userSetting'),
    path('setadmin/<int:userid>/', setAdmin, name='setAdmin'),
    path('resetadmin/<int:userid>/', resetAdmin, name='resetAdmin'),
]

Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from Blog.views import *
app_name = 'Blog'
urlpatterns = [
    path('index/', index, name='index'),
    path('posting/', posting),
]

NBAStream/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
app_name = 'NBAStream'
urlpatterns = [
    path('index/', index, name='index'),
    path('gameinfo/<int:gameid>/', gameInfo, name='GameInfo'),
]

Test/urls.py
from django.urls import path, include
import NBAStream.views
urlpatterns = [
    path('', NBAStream.views.index),
    path('web/', include("Web.urls", namespace='web')),
    path('user/', include("User.urls", namespace='user')),
    path('nbastream/', include("NBAStream.urls", namespace='nbastream')),
    path('admin/', include("Admin.urls", namespace='admin')),
    path('blog/', include("Blog.urls", namespace='blog'),),

]

User/urls.py
from django.urls import path, re_path
from .views import *
app_name = 'User'
urlpatterns = [
    path('index/', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    re_path('^setting/(?:(?P<flag>\w+)/(page-(?P<current_page>\d+)/)?)?', setting, name="setting"),
]

Web/urls.py
from django.urls import path, re_path
from .views import *
app_name = 'Web'
urlpatterns = [
    path('about/', about, name='about'),
    re_path('^notice/(?:page-(?P<noticeid>\d+)/)?', notice, name='notice'),
    path('board/', board, name='board-na'),
    path('board/<int:current_page>/', board, name='board'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    {% block head %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
        html { position: relative; min-height: 100%; }
        body { margin-bottom: 60px; }
        .footer { position: absolute; bottom: 0; width: 100%; height: 60px; line-height: 60px; background-color: #f5f5f5; }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-sm-5">
            <a class="navbar-brand" href="/">Parker</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <!--
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Blog:index' %} ">Blog</a>
                    </li>
                    -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "NBAStream:index" %}">NBA直播</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url "Web:board-na" %}">留言板</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "Web:about" %}">关于</a>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-right">
                    {% if myuser %}
                        <li class="nav-item">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">欢迎您，{{ myuser.username }}</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'User:setting' %}">个人中心</a>
                                    {% if myuser.type == 1 %}
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url "Admin:index" %}">网站管理</a>
                                    {% endif %}
                                </div>
                            </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'User:logout' %} ">退出</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'User:login' %} ">登录</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'User:register' %} ">注册</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    {% block body %}{% endblock %}
    <footer class="footer">
        <div class="text-center">
          <span>Copyright © 2017-2018</span>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/main.html
{% extends "base.html" %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-9">
                {% block content %}{% endblock %}
            </div>
            <div class="col-sm-3">
                <div class="card mb-sm-4">
                    <h5 class="card-header bg-dark text-white">公告</h5>
                        {% if not recent_notice %}
                            <p class="text-center mt-sm-3">暂无</p>
                        {% endif %}
                        {% for item in recent_notice %}
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item list-group-item-action">
                                    <a class="link" href="{% url "Web:notice" %}page-{{ item.id }}/">{{ item.title }}</a>
                                </li>
                            </ul>
                        {% endfor %}
                </div>

                <div class="card mb-sm-4">
                    <h5 class="card-header bg-dark text-white">最近访客</h5>
                    <ul class="list-group list-group-flush">
                        {% if not recent_visitor %}
                            <p class="text-center mt-sm-3">暂无</p>
                        {% endif %}
                        {% for item in recent_visitor %}
                            <li class="list-group-item list-group-item-action">
                            {% if item.user %}
                                <span><strong>{{ item.user.username }}</strong>:{{ item.visitTime|date:"Y-m-d H:i:s" }}</span>
                            {% else %}
                                <span><strong>{{ item.ip }}</strong>:{{ item.visitTime|date:"Y-m-d H:i:s" }}</span>
                            {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="card mb-sm-4">
                    <h5 class="card-header bg-dark text-white">
                        最新留言
                    </h5>
                    <ul class="list-group list-group-flush">
                    {% autoescape off %}
                        {% if not recent_message %}
                            <p class="text-center mt-sm-3">暂无</p>
                        {% endif %}
                        {% for item in recent_message %}
                            <li class="list-group-item list-group-item-action">
                                <div class="media">
                                    <img class="align-self-start rounded-circle d-block" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="60" height="60">
                                    <div class="media-body ml-sm-3">
                                        <strong>{{ item.user.username }}：</strong>
                                        <p>{{ item.content }}</p>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                        {% block board %}{% endblock %}
                    {% endautoescape %}
                        <a href="{% url "Web:board-na" %}" class="list-group-item list-group-item-action">
                            <div class="text-center">
                                查看全部留言
                            </div>
                        </a>
                    </ul>
                        {% if message_error_message %}
                            <p>{{ message_error_message }}</p>
                        {% endif %}
                        {% if message_success_message %}
                            <p>{{ message_success_message }}</p>
                        {% endif %}
                        <form action="{% url "Web:board" 1 %}" method="post" class="form-group">
                            <div class="row mt-sm-3">
                                <div class="col-sm-9">
                                    {% csrf_token %}
                                    <input name="content" type="text" placeholder="请输入您的留言" class="form-control ml-sm-2">
                                </div>
                                <div class="col-sm-3">
                                    <input type="submit" value="发表" class="btn btn-primary mr-sm-2">
                                </div>
                            </div>
                        </form>
                </div>
                {% block sidebar %}{% endblock %}
            </div>
        </div>
        {% block others %}{% endblock %}
    </div>
{% endblock %}