Test/urls.py
from django.urls import path, include
import NBAStream.views
urlpatterns = [
    path('', NBAStream.views.index),
    path('web/', include("Web.urls", namespace='web')),
    path('user/', include("User.urls", namespace='user')),
    path('nbastream/', include("NBAStream.urls", namespace='nbastream')),
    path('admin/', include("Admin.urls", namespace='admin')),
    path('blog/', include("Blog.urls", namespace='blog'),),

]

Web/urls.py
from django.urls import path, re_path
from .views import *
app_name = 'Web'
urlpatterns = [
    path('about/', about, name='about'),
    re_path('^notice/(?:page-(?P<noticeid>\d+)/)?', notice, name='notice'),
    path('board/', board, name='board-na'),
    path('board/<int:current_page>/', board, name='board'),
]

Web/templates/Web/about.html
{% extends "base.html" %}
{% block body %}
    <div class="container">
        <div class="col-sm-12">
            <h2>关于</h2>
        </div>
    </div>
{% endblock %}

{% block head %}
    <title>关于</title>
{% endblock %}

Web/templates/Web/board.html
{% extends "main.html" %}
{% block content %}
    {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
    {% endif %}
    {% if success_message %}
        <p class="text-success">{{ success_message }}</p>
    {% endif %}
    <form action="{% url "Web:board" 1 %}" method="post" class=" mb-sm-4">
        {% csrf_token %}
        <textarea name="content" id="editor1" class="form-control"></textarea>
        <script>
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace( 'editor1' );
        </script>
        <input type="submit" value="发表" class="btn btn-primary btn-lg float-right mt-sm-4">
        <div class="clearfix"></div>
    </form>
    {% for item in show_message %}
    <div class="card mb-sm-4">
        <div class="row" style="padding: 10px;">
            <div class="col-sm-2">
                <img class="rounded-circle mx-auto d-block" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="60" height="60">
                <div class="text-center">
                    <strong>{{ item.user.username }}</strong>
                </div>
            </div>
            <div class="col-sm-10">
                {% autoescape off %}
                    <p class="card-text">
                        {{ item.content }}
                    </p>
                {% endautoescape %}

                <div class="text-right">
                    {{ item.createTime|date:"Y-m-d H:i:s" }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
	{% if page_list %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if current_page != 1 %}
            <li class="page-item">
                <a class="page-link" href="{% url "Web:board" previous_page %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        {% endif %}
            {% for i in page_list %}
                {% if i != current_page %}
                    <li class="page-item">
                {% else %}
                    <li class="page-item active">
                {% endif %}
                <a class="page-link" href="{% url "Web:board" i %}">{{ i }}</a>
            </li>
            {% endfor %}
        {% if current_page != last_page %}
            <li class="page-item">
                <a class="page-link" href="{% url "Web:board" next_page %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        {% endif %}
        </ul>
    </nav>
	{% endif %}

{% endblock %}
{% block head %}
    <title>留言板</title>
    {% load staticfiles %}
    <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
{% endblock %}

Web/templates/Web/notice.html
{% extends "main.html" %}
{% block content %}
    <h2 class="text-center">{{ item.title }}</h2>
    <h4>
        <div class="text-right">
            <small class="text-muted mr-sm-4">发布者：{{ item.admin.username }}</small>
            <small class="text-muted">发布时间：{{ item.createTime|date:"Y-m-d H:i:s" }}</small>
        </div>
    </h4>
    <p>{{ item.content|safe }}</p>
{% endblock %}